config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :set_clients, only: %i[ new edit create destroy update]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def set_clients
      @clients = Client.all.pluck :name, :id
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <tr>
    <th scope="row"><%= client.id %></th>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
    <td><%= client.movies.last %></td>
    <td><%= link_to "Detalle del Cliente", client %></td>
    <td><%= link_to "Editar Cliente", edit_client_path(client) %></td>
    <td><%= button_to "Eliminar Cliente", @client, method: :delete, class: "boton-amarillo" %></td>
  </tr>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Nombre", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, "Edad", style: "display: block" %>
    <%= form.text_field :age %>
  </div>
  <br>

  <div>
    <%= form.submit "Guardar Cliente" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Detalle del Cliente", @client %> |
  <%= link_to "Volver a Clientes", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Clientes</h1>

  <%= link_to "Nuevo Cliente", new_client_path %>

  <div id="clients">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre</th>
          <th scope="col">Edad</th>
          <th scope="col">Pelicula</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <%= render client %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.select :client_id, options_for_select(@clients) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
  <div class="col-4 py-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= movie.name %></h5>
        <%= link_to "Mostrar esta pelicula", movie, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

app/views/movies/edit.html.erb
<h1>Editando la pelicula</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Mostrar esta pelicula", @movie %> |
  <%= link_to "Volver a peliculas", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Peliculas</h1>
  <%= link_to "Nueva pelicula", new_movie_path %>
  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <%= render movie %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Editar esta pelicula", edit_movie_path(@movie) %> |
  <%= link_to "Volver a peliculas", movies_path %>

  <%= button_to "Eliminar esta pelicula", @movie, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary
">
  <div class="container">
    <%= link_to 'BlockBuster', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="links-navbar position-absolute top-2 end-50">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item ms-5">
              <%= link_to 'Clientes', clients_path, class: 'nav-link' %>
            </li>
            <li class="nav-item ms-4">
              <%= link_to 'Peliculas', movies_path, class: 'nav-link' %>
            </li>
      </ul>
    </div>
      </div>
  </div>
</nav>